import { Video } from '../types';

export const VIDEOS: Video[] = [
  { "id": "6MePWbeLERU", "title": "The Animal Sounds Song", "views": "12M", "category": "Learning" },
  { "id": "vTulGqpD9eE", "title": "The ABC Song", "views": "250M", "category": "Learning" },
  { "id": "ozHbtAdg1f4", "title": "Shapes Song for Kids", "views": "88M", "category": "Learning" },
  { "id": "ZkAnZNEcKCE", "title": "Counting 1 to 10", "views": "120M", "category": "Learning" },
  { "id": "K0klXRLfiRA", "title": "Five Little Ducks", "views": "1.1B", "category": "Rhymes" },
  { "id": "rXxYPiDCRu4", "title": "Old MacDonald Had a Farm", "views": "500M", "category": "Rhymes" },
  { "id": "xdqtY2cEHzE", "title": "The Wheels on the Bus", "views": "2.3B", "category": "Rhymes" },
  { "id": "HGQFmnA3ehE", "title": "Baby Shark Dance", "views": "10B", "category": "Rhymes" },
  { "id": "nyy9qLXgl4c", "title": "The Tortoise and the Hare", "views": "45M", "category": "Stories" },
  { "id": "yUA1kE-71pk", "title": "The Lion and the Mouse", "views": "60M", "category": "Stories" },
  { "id": "vPnf9YUJaqU", "title": "Three Little Pigs", "views": "105M", "category": "Stories" },
  { "id": "u6FGNdQxLmQ", "title": "The Gingerbread Man", "views": "33M", "category": "Stories" },
  { "id": "7XG1ZJ1CCSw", "title": "Itsy Bitsy Spider", "views": "800M", "category": "Rhymes" },
  { "id": "ztZUbjo602E", "title": "Row Row Row Your Boat", "views": "450M", "category": "Rhymes" },
  { "id": "vUZ_ShBI9-A", "title": "Humpty Dumpty", "views": "300M", "category": "Rhymes" },
  { "id": "ZzCsAYltgxM", "title": "Phonics Song with Two Words", "views": "1.5B", "category": "Learning" },
  { "id": "lQnqHyt4Oio", "title": "Days of the Week Song", "views": "95M", "category": "Learning" },
  { "id": "zMzhGNHq-Hw", "title": "Months of the Year Song", "views": "75M", "category": "Learning" },
  { "id": "Qk5u0MstATY", "title": "The Little Red Hen", "views": "28M", "category": "Stories" },
  { "id": "tEeWbRr2kDg", "title": "Goldilocks and the Three Bears", "views": "92M", "category": "Stories" },
  { "id": "ryyK-Kx7g5I", "title": "Jack and the Beanstalk", "views": "41M", "category": "Stories" },
  { "id": "HhzVCfdGVRA", "title": "Baa Baa Black Sheep", "views": "2.1B", "category": "Rhymes" },
  { "id": "EJYYLP8lbVM", "title": "Mary Had a Little Lamb", "views": "750M", "category": "Rhymes" },
  { "id": "RxrZ6u8OrEA", "title": "Hickory Dickory Dock", "views": "600M", "category": "Rhymes" },
  { "id": "P2zzYFsciM4", "title": "Clean Up Song", "views": "550M", "category": "Learning" },
  { "id": "4yuGvyrIddU", "title": "Brush Your Teeth", "views": "400M", "category": "Learning" },
  { "id": "k1eE7jcm0Zw", "title": "The Ugly Duckling", "views": "80M", "category": "Stories" },
  { "id": "lh_N8Nrjmy8", "title": "The Ant and the Grasshopper", "views": "55M", "category": "Stories" },
  { "id": "kK4NER-Twjg", "title": "Twinkle Twinkle Little Star", "views": "3B", "category": "Rhymes" },
  { "id": "pxWBpAL2V-w", "title": "If You're Happy and You Know It", "views": "1.8B", "category": "Rhymes" },
  { "id": "CsjeotE-hKI", "title": "Head Shoulders Knees & Toes", "views": "1.2B", "category": "Learning" },
  { "id": "rBKo2-hAFvc", "title": "Johny Johny Yes Papa", "views": "4B", "category": "Stories" },
  { "id": "ghROtGucltU", "title": "The Fox and the Crow", "views": "22M", "category": "Stories" },
  { "id": "oHrAoJ492gc", "title": "The Thirsty Crow", "views": "18M", "category": "Stories" }
];